### ISSUE TITLE
メッセージ文字列を記憶する

### ISSUE THREAD

**Issue by katahiromz** [katahiromz/KraKra_ja_jp#15]
指定したメッセージ文字列が、リスト内になければ、リストの末尾にその文字列の項目を追加する。
「アプリ初期化」ボタンを押したら、追加した項目を忘れる。

**Comment by katahiromz** [comment]
https://codechacha.com/ja/android-shared-preferences/

**Comment by yukinkomob** [comment]
> 指定したメッセージ文字列が、リスト内になければ、リストの末尾にその文字列の項目を追加する。
> 「アプリ初期化」ボタンを押したら、追加した項目を忘れる。

下記のようなイメージで合ってますか？

* メッセージダイアログで一度入力した文字列はリストに追加される
* メッセージダイアログで既にリストに追加済みの文字列は、入力してもリストに重複して追加されることはない
* メッセージダイアログのリストは、初期文字列群＋過去の入力履歴のような位置付けである
* アプリ初期化ボタンを押下すると、過去の入力履歴部分がクリアされる（初期文字列群は維持される）

**Comment by katahiromz** [comment]
その通りです。

**Comment by yukinkomob** [comment]
### 入力メッセージの登録機能

* メッセージダイアログで一度入力した文字列はリストに追加される
* メッセージダイアログで既にリストに追加済みの文字列は、入力してもリストに重複して追加されることはない
* ダイアログのリストは5項目まで表示可。それ以上はスクロールにて表示
* アプリ初期化ボタンを押下すると、過去の入力履歴部分がクリアされる（初期文字列群は維持される）

操作動画：
https://drive.google.com/file/d/1Scnj7yxXkf0sgQOkcu2v2A8KIpTrchn6/view?usp=sharing
