### ISSUE TITLE
アプリ初期化を実行するとインターネットの接続エラーページが表示される

### ISSUE THREAD

**Issue by yukinkomob** [katahiromz/KraKra_ja_jp#17]
### 背景

起動時間の短縮を目的としてWebアプリ周りのコードをAndroid側のassetsフォルダに確認したことにより、再現するようになった

**Comment by katahiromz** [comment]
現状では、`onReceivedError` / `onReceivedHttpError`でページ読み込み失敗をキャッチしている。
`success = false` して、`onPageFinished`で`success`が`false`ならば`webView.loadUrl(getString(R.string.failed_url))`する。これにより失敗ページが表示される。

**Comment by katahiromz** [comment]
`R.string.failed_url`はアセットの`net_fail.html`を指している。

**Comment by katahiromz** [comment]
https://github.com/katahiromz/KraKra_ja_jp/commit/60da661f71d6e611c456d3d2b93978deb2d55663
これで解決。
