### ISSUE TITLE
ネイティブ側の安定性問題の精査および改修対応

### ISSUE THREAD

**Issue by yukinkomob** [katahiromz/KraKra_ja_jp#3]

**Comment by katahiromz** [comment]
了解。

**Comment by yukinkomob** [comment]
他のmustのタスクが終わった後、Google Play Consoleにて最新版の安定性問題の有無を確認し、必要があれば対応をする。

**Comment by katahiromz** [comment]
![image](https://user-images.githubusercontent.com/2107452/176437704-e600b5ee-9ec7-45bf-8d71-71242aa3f023.png)
解決しました。
