### ISSUE TITLE
ネイティブ側のスプラッシュ画面のアイコン表示問題の精査および改修対応

### ISSUE THREAD

**Issue by yukinkomob** [katahiromz/KraKra_ja_jp#4]
### 依頼内容

![Screen Shot 2022-06-20 at 21 45 25](https://user-images.githubusercontent.com/3205581/174604726-82991dcf-3ed9-40bd-817e-6a3a5aba3d30.png)

**Comment by katahiromz** [comment]
了解。

**Comment by yukinkomob** [comment]
### アイコンが違う.png

![アイコンが違う](https://user-images.githubusercontent.com/3205581/174688205-cd0c45f0-c6a4-4056-a407-29b28a38eab3.png)

**Comment by yukinkomob** [comment]
<img width="582" alt="Screen Shot 2022-06-22 at 12 39 10" src="https://user-images.githubusercontent.com/3205581/174938430-f775d683-dad8-402a-8d5c-ea2d7030e7e9.png">

![icon-maskable](https://user-images.githubusercontent.com/3205581/174938489-ed982486-0f5f-47f3-b5cc-1318c1b00ba7.svg)

![icon-maskable](https://user-images.githubusercontent.com/3205581/174938484-9eba8c24-9aa6-4fac-bdba-5cef1c2352dd.png)

**Comment by yukinkomob** [comment]
スプラッシュ画面  |  Android デベロッパー  |  Android Developers
https://developer.android.com/guide/topics/ui/splash-screen?hl=ja

**Comment by yukinkomob** [comment]
### 修正前後の表示

|変更前|変更後|
|----|----|
|<img width="304" alt="Screen Shot 2022-06-22 at 12 57 59" src="https://user-images.githubusercontent.com/3205581/174940651-82112822-3c4a-4262-98e5-5fee4e7d42f4.png">|<img width="293" alt="Screen Shot 2022-06-22 at 13 00 35" src="https://user-images.githubusercontent.com/3205581/174940659-763196a2-fdc6-4aa1-a057-4d207b4c7e68.png">|

画面の上側に背景が適用されていないように見えますが、アニメーション中に撮影したスクショなので、このようになっています。
下記の動画を参考にしてください。

https://user-images.githubusercontent.com/3205581/174941079-50067b94-4e12-4a5f-8ea0-22dbf05c4531.mov

**Comment by katahiromz** [comment]
こちらで対処しました。
https://github.com/katahiromz/KraKra_ja_jp/commit/f6b292066ccc21b40218edc95dd8c059ac1c7d5d

Adaptive iconにすると直りました。
![無題](https://user-images.githubusercontent.com/2107452/174948645-6e11e620-2ab4-4b01-a161-ecdc61c96311.png)
