### ISSUE TITLE
起動待機時間が長い問題の原因調査および改修対応

### ISSUE THREAD

**Issue by yukinkomob** [katahiromz/KraKra_ja_jp#5]

**Comment by katahiromz** [comment]
了解。

**Comment by katahiromz** [comment]
起動待ち時間を実測して下さい(キャッシュなし、初回)。
可能ならば、スプラッシュ画面の後で画面中央に「アプリ起動中...」を表示して下さい。
待ち時間をなるべく短くして下さい。短縮できた時間を報告下さい。

**Comment by yukinkomob** [comment]
### 起動時の撮影動画

ランチャーアイコン押下：1'82 時点
アプリ画面起動：3'11 時点
起動時間：1秒290ミリ秒

https://user-images.githubusercontent.com/3205581/175812240-33e4dc4b-39a7-4dd9-ae49-51ad7a7b7391.mov

**Comment by katahiromz** [comment]
起動時間が１秒ちょっとくらいなら、それほど気にする必要はなさそうですね。
ネットワークが遅延したときに問題が起こる可能性はありそうですが。

**Comment by yukinkomob** [comment]
追加で5回ほど測定してみました。

01:00 - 01:76：0秒760ミリ秒
16:47 - 17:06 : 0秒590ミリ秒
27:29 - 28:23 : 0秒540ミリ秒
38:06 - 38:88：0秒820ミリ秒
48:29 - 49:17：0秒880ミリ秒

動画
https://drive.google.com/file/d/15vWBzQhQ2T0gHcCrIuXws-nSII89OxzB/view?usp=sharing

**Comment by katahiromz** [comment]
ネットワーク遅延が起きたときに、白い画面で固まらずに「起動中...」を表示すると、ユーザのストレスが軽減できると思います。

**Comment by yukinkomob** [comment]
現状計測した限りでは起動時間が問題になることはなさそうですね。

下記について対応します。
> ネットワーク遅延が起きたときに、白い画面で固まらずに「起動中...」を表示すると、ユーザのストレスが軽減できると思います。

**Comment by yukinkomob** [comment]
あとはGoogle Play Consoleでリリースした後の話になりますが、Android Vitals で起動時間のパフォーマンスデータの計測が行われるはずなので、そちらで状況を確認して、対応を検討して頂ければよろしいかと思います。

Google Developers Japan: Android Vitals を活用してアプリの品質の問題を解決し、Play ストアでのパフォーマンスを向上させる方法（パート 1）
https://developers-jp.googleblog.com/2018/11/How-to-fix-app-quality-issues-with-Android-vital.html

**Comment by yukinkomob** [comment]
### 対応内容

* WebViewの背景色をWebページの初期起動時の背景と同色にした
    * これにより白画面を挟むことがなくなった
* WebViewの上に「起動中...」の文字列を配置
    * WebViewがページの読み込みを完了（onPageFinished）したら文字列を非表示にした

参考動画：

https://user-images.githubusercontent.com/3205581/175814586-ec71fe01-af50-438c-9594-1e52b3a898e5.mov

* 起動時間が短いため一瞬ですが、「起動中...」の文字列を表示しています
* ページ読み込み後は「起動中...」の文字列が非表示となっています
* 起動時に白画面を挟まない形に変更されています

**Comment by yukinkomob** [comment]
### 起動中に表示される画面

![Screen Shot 2022-06-26 at 22 04 20](https://user-images.githubusercontent.com/3205581/175815457-c53cb9c8-3b51-4c20-a53f-abfb0e85ad25.png)

**Comment by katahiromz** [comment]
![performance-problem](https://user-images.githubusercontent.com/2107452/176076812-09424f06-c928-4e25-98ae-a024b5b7728c.png)
初回起動時にパフォーマンスの問題が起こっているようです。対策として：

- Webプログラムをアセットに埋め込む。
- 起動処理を別スレッドにする。

のいずれかを考えています。

**Comment by katahiromz** [comment]
`TextToSpeech` は後回しにした方がいいと思います。

**Comment by katahiromz** [comment]
assetsにWebを追加しました。

**Comment by katahiromz** [comment]
ライフサイクル周辺が間違っている可能性があります。
再確認をお願いします。

**Comment by yukinkomob** [comment]
アプリの起動時間  |  Android デベロッパー  |  Android Developers
https://developer.android.com/topic/performance/vitals/launch-time?hl=ja

**Comment by yukinkomob** [comment]
### アプリファイルのサイズ

デバッグ版で 3.4 MB 程度なので特に影響があるとは思えない。

<img width="478" alt="Screen Shot 2022-06-28 at 21 04 57" src="https://user-images.githubusercontent.com/3205581/176174240-d42fbb89-7796-4245-b5ca-b170bdde79f5.png">
