### ISSUE TITLE
「アプリ初期化」ボタンの動作確認・修正

### ISSUE THREAD

**Issue by yukinkomob** [katahiromz/KraKra_ja_jp#6]

**Comment by katahiromz** [comment]
了解。

**Comment by yukinkomob** [comment]
アプリ初期化ボタンを押下した後、画面がフリーズする

**Comment by katahiromz** [comment]
> アプリ初期化ボタンを押下した後、画面がフリーズする

これはもう直ったと思います。

**Comment by yukinkomob** [comment]
> これはもう直ったと思います。

フリーズが発生しなくなっていることを確認しました。

追加で気になる箇所があります。
アプリの初期化ボタンを押した後、アラートダイアログが表示しますが、それをタップした後、まだ最初のダイアログが残っているため、違和感があります。
アプリの初期化ボタンが押された時点で、最初のダイアログは閉じるべきと思います。

https://user-images.githubusercontent.com/3205581/175814961-af317b83-844b-48ac-b167-0fa6ad68974f.mov

**Comment by katahiromz** [comment]
> アプリの初期化ボタンが押された時点で、最初のダイアログは閉じるべきと思います。

修正しました。
