### ISSUE TITLE
web 側の service-worker の動作確認・修正

### ISSUE THREAD

**Issue by yukinkomob** [katahiromz/KraKra_ja_jp#7]
### 依頼内容

![Screen Shot 2022-06-20 at 21 45 25](https://user-images.githubusercontent.com/3205581/174604610-979d1d35-e3d3-4deb-9ee3-57d69d2400ad.png)

**Comment by katahiromz** [comment]
了解。

**Comment by yukinkomob** [comment]
下記へ移動
https://github.com/katahiromz/katahiromz.github.io/issues/1
